#
# Copyright (c) 2022 ZettaScale Technology
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ZettaScale Zenoh Team, <zenoh@zettascale.tech>
#
name: mbed

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          echo "No requirements need to be installed"

      - name: Install PlatformIO
        run: |
          curl -fsSL -o get-platformio.py https://raw.githubusercontent.com/platformio/platformio-core-installer/master/get-platformio.py
          python3 get-platformio.py
          . $HOME/.platformio/penv/bin/activate
          platformio update

      - name: Set up project
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/
          . $HOME/.platformio/penv/bin/activate

          mkdir -p $MBED_BASE
          cd $MBED_BASE
          pio init -b nucleo_f767zi --project-option="framework=mbed" --project-option="build_flags=-DZ_FEATURE_LINK_SERIAL=1 -DZENOH_DEBUG=3 -DZENOH_COMPILER_GCC"

          cd $MBED_BASE/lib
          ln -s $ZENOH_PICO_BASE

          cd $MBED_BASE

      - name: Build z_pub example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/
          . $HOME/.platformio/penv/bin/activate

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_pub.cpp

          cd $MBED_BASE
          platformio run

      - name: Build z_sub example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/
          . $HOME/.platformio/penv/bin/activate

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_sub.cpp

          cd $MBED_BASE
          platformio run

      - name: Build z_pull example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/
          . $HOME/.platformio/penv/bin/activate

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_pull.cpp

          cd $MBED_BASE
          platformio run

      - name: Build z_get example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/
          . $HOME/.platformio/penv/bin/activate

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_get.cpp

          cd $MBED_BASE
          platformio run

      - name: Build z_queryable example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/
          . $HOME/.platformio/penv/bin/activate

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_queryable.cpp

          cd $MBED_BASE
          platformio run

      - name: Build z_scout example
        run: |
          cd $HOME
          export MBED_BASE=$HOME/work/mbedproject/
          export ZENOH_PICO_BASE=$HOME/work/zenoh-pico/zenoh-pico/
          . $HOME/.platformio/penv/bin/activate

          rm -rf $MBED_BASE/src/*
          cd $MBED_BASE/src
          ln -s $ZENOH_PICO_BASE/examples/mbed/z_scout.cpp

          cd $MBED_BASE
          platformio run
